/***********************************************************************
*                                                                      *
*               This software is part of the ast package               *
*          Copyright (c) 1985-2010 AT&T Intellectual Property          *
*                      and is licensed under the                       *
*                  Common Public License, Version 1.0                  *
*                    by AT&T Intellectual Property                     *
*                                                                      *
*                A copy of the License is available at                 *
*            http://www.opensource.org/licenses/cpl1.0.txt             *
*         (with md5 checksum 059e8cd6165cb4c31e351f2b69388fd9)         *
*                                                                      *
*              Information and Software Systems Research               *
*                            AT&T Research                             *
*                           Florham Park NJ                            *
*                                                                      *
*                 Glenn Fowler <gsf@research.att.com>                  *
*                  David Korn <dgk@research.att.com>                   *
*                   Phong Vo <kpv@research.att.com>                    *
*                                                                      *
***********************************************************************/

/* : : generated by proto : : */

#if !defined(__PROTO__)
#  if defined(__STDC__) || defined(__cplusplus) || defined(_proto) || defined(c_plusplus)
#    if defined(__cplusplus)
#      define __LINKAGE__	"C"
#    else
#      define __LINKAGE__
#    endif
#    define __STDARG__
#    define __PROTO__(x)	x
#    define __OTORP__(x)
#    define __PARAM__(n,o)	n
#    if !defined(__STDC__) && !defined(__cplusplus)
#      if !defined(c_plusplus)
#      	define const
#      endif
#      define signed
#      define void		int
#      define volatile
#      define __V_		char
#    else
#      define __V_		void
#    endif
#  else
#    define __PROTO__(x)	()
#    define __OTORP__(x)	x
#    define __PARAM__(n,o)	o
#    define __LINKAGE__
#    define __V_		char
#    define const
#    define signed
#    define void		int
#    define volatile
#  endif
#  define __MANGLE__	__LINKAGE__
#  if defined(__cplusplus) || defined(c_plusplus)
#    define __VARARG__	...
#  else
#    define __VARARG__
#  endif
#  if defined(__STDARG__)
#    define __VA_START__(p,a)	va_start(p,a)
#  else
#    define __VA_START__(p,a)	va_start(p)
#  endif
#  if !defined(__INLINE__)
#    if defined(__cplusplus)
#      define __INLINE__	extern __MANGLE__ inline
#    else
#      if defined(_WIN32) && !defined(__GNUC__)
#      	define __INLINE__	__inline
#      endif
#    endif
#  endif
#endif
#if !defined(__LINKAGE__)
#define __LINKAGE__		/* 2004-08-11 transition */
#endif
#include "FEATURE/lib"
#if _hdr_limits
#include <limits.h>
#endif
#if _hdr_unistd
#include <unistd.h>
#endif
#include "confmap.h"

/* : : generated by conf from /home/gsf/src/lib/libast/comp/conf.tab : : */

/*
 * enum used on an extensible namespace -- bad idea
 */

#define _ENUM__SC_ADVISORY_INFO	1
#define _ENUM__SC_AIO_LISTIO_MAX	1
#define _ENUM__SC_AIO_MAX	1
#define _ENUM__SC_AIO_PRIO_DELTA_MAX	1
#define _ENUM__PC_ALLOC_SIZE_MIN	1
#define _ENUM__SC_ARG_MAX	1
#define _ENUM__SC_ASYNCHRONOUS_IO	1
#define _ENUM__PC_ASYNC_IO	1
#define _ENUM__SC_ATEXIT_MAX	1
#define _ENUM__SC_AVPHYS_PAGES	1
#define _ENUM__SC_BARRIERS	1
#define _ENUM__SC_BASE	1
#define _ENUM__SC_BC_BASE_MAX	1
#define _ENUM__SC_BC_DIM_MAX	1
#define _ENUM__SC_BC_SCALE_MAX	1
#define _ENUM__SC_BC_STRING_MAX	1
#define _ENUM__SC_CHARCLASS_NAME_MAX	1
#define _ENUM__SC_CHAR_BIT	1
#define _ENUM__SC_CHAR_MAX	1
#define _ENUM__SC_CHAR_MIN	1
#define _ENUM__SC_2_CHAR_TERM	1
#define _ENUM__SC_CHILD_MAX	1
#define _ENUM__PC_CHOWN_RESTRICTED	1
#define _ENUM__SC_CLK_TCK	1
#define _ENUM__SC_CLOCK_SELECTION	1
#define _ENUM__SC_COLL_WEIGHTS_MAX	1
#define _ENUM__SC_CPUTIME	1
#define _ENUM__SC_XOPEN_CRYPT	1
#define _ENUM__SC_2_C_BIND	1
#define _ENUM__SC_2_C_DEV	1
#define _ENUM__SC_2_C_VERSION	1
#define _ENUM__SC_DELAYTIMER_MAX	1
#define _ENUM__SC_DEVICE_IO	1
#define _ENUM__SC_DEVICE_SPECIFIC	1
#define _ENUM__SC_DEVICE_SPECIFIC_R	1
#define _ENUM__SC_XOPEN_ENH_I18N	1
#define _ENUM__SC_EQUIV_CLASS_MAX	1
#define _ENUM__SC_EXPR_NEST_MAX	1
#define _ENUM__SC_FD_MGMT	1
#define _ENUM__SC_FIFO	1
#define _ENUM__PC_FILESIZEBITS	1
#define _ENUM__SC_FILE_ATTRIBUTES	1
#define _ENUM__SC_FILE_LOCKING	1
#define _ENUM__SC_FILE_SYSTEM	1
#define _ENUM__SC_2_FORT_DEV	1
#define _ENUM__SC_2_FORT_RUN	1
#define _ENUM__SC_FSYNC	1
#define _ENUM__SC_GETGR_R_SIZE_MAX	1
#define _ENUM__SC_GETPW_R_SIZE_MAX	1
#define _ENUM__SC_HOST_NAME_MAX	1
#define _ENUM__SC_XBS5_ILP32_OFF32	1
#define _ENUM__CS_XBS5_ILP32_OFF32_CFLAGS	1
#define _ENUM__CS_XBS5_ILP32_OFF32_LDFLAGS	1
#define _ENUM__CS_XBS5_ILP32_OFF32_LIBS	1
#define _ENUM__CS_XBS5_ILP32_OFF32_LINTFLAGS	1
#define _ENUM__SC_XBS5_ILP32_OFFBIG	1
#define _ENUM__CS_XBS5_ILP32_OFFBIG_CFLAGS	1
#define _ENUM__CS_XBS5_ILP32_OFFBIG_LDFLAGS	1
#define _ENUM__CS_XBS5_ILP32_OFFBIG_LIBS	1
#define _ENUM__CS_XBS5_ILP32_OFFBIG_LINTFLAGS	1
#define _ENUM__SC_INT_MAX	1
#define _ENUM__SC_INT_MIN	1
#define _ENUM__SC_IOV_MAX	1
#define _ENUM__SC_IPV6	1
#define _ENUM__SC_JOB_CONTROL	1
#define _ENUM__SC_C_LANG_SUPPORT	1
#define _ENUM__SC_C_LANG_SUPPORT_R	1
#define _ENUM__SC_XOPEN_LEGACY	1
#define _ENUM__SC_LEVEL1_DCACHE_ASSOC	1
#define _ENUM__SC_LEVEL1_DCACHE_LINESIZE	1
#define _ENUM__SC_LEVEL1_DCACHE_SIZE	1
#define _ENUM__SC_LEVEL1_ICACHE_ASSOC	1
#define _ENUM__SC_LEVEL1_ICACHE_LINESIZE	1
#define _ENUM__SC_LEVEL1_ICACHE_SIZE	1
#define _ENUM__SC_LEVEL2_CACHE_ASSOC	1
#define _ENUM__SC_LEVEL2_CACHE_LINESIZE	1
#define _ENUM__SC_LEVEL2_CACHE_SIZE	1
#define _ENUM__SC_LEVEL3_CACHE_ASSOC	1
#define _ENUM__SC_LEVEL3_CACHE_LINESIZE	1
#define _ENUM__SC_LEVEL3_CACHE_SIZE	1
#define _ENUM__SC_LEVEL4_CACHE_ASSOC	1
#define _ENUM__SC_LEVEL4_CACHE_LINESIZE	1
#define _ENUM__SC_LEVEL4_CACHE_SIZE	1
#define _ENUM__CS_LFS64_CFLAGS	1
#define _ENUM__CS_LFS64_LDFLAGS	1
#define _ENUM__CS_LFS64_LIBS	1
#define _ENUM__CS_LFS64_LINTFLAGS	1
#define _ENUM__CS_LFS_CFLAGS	1
#define _ENUM__CS_LFS_LDFLAGS	1
#define _ENUM__CS_LFS_LIBS	1
#define _ENUM__CS_LFS_LINTFLAGS	1
#define _ENUM__CS_GNU_LIBC_VERSION	1
#define _ENUM__CS_GNU_LIBPTHREAD_VERSION	1
#define _ENUM__SC_LINE_MAX	1
#define _ENUM__PC_LINK_MAX	1
#define _ENUM__SC_2_LOCALEDEF	1
#define _ENUM__SC_LOGIN_NAME_MAX	1
#define _ENUM__SC_LONG_BIT	1
#define _ENUM__SC_XBS5_LP64_OFF64	1
#define _ENUM__CS_XBS5_LP64_OFF64_CFLAGS	1
#define _ENUM__CS_XBS5_LP64_OFF64_LDFLAGS	1
#define _ENUM__CS_XBS5_LP64_OFF64_LIBS	1
#define _ENUM__CS_XBS5_LP64_OFF64_LINTFLAGS	1
#define _ENUM__SC_XBS5_LPBIG_OFFBIG	1
#define _ENUM__CS_XBS5_LPBIG_OFFBIG_CFLAGS	1
#define _ENUM__CS_XBS5_LPBIG_OFFBIG_LDFLAGS	1
#define _ENUM__CS_XBS5_LPBIG_OFFBIG_LIBS	1
#define _ENUM__CS_XBS5_LPBIG_OFFBIG_LINTFLAGS	1
#define _ENUM__SC_MAPPED_FILES	1
#define _ENUM__PC_MAX_CANON	1
#define _ENUM__PC_MAX_INPUT	1
#define _ENUM__SC_MB_LEN_MAX	1
#define _ENUM__SC_MEMLOCK	1
#define _ENUM__SC_MEMLOCK_RANGE	1
#define _ENUM__SC_MEMORY_PROTECTION	1
#define _ENUM__SC_MESSAGE_PASSING	1
#define _ENUM__SC_MONOTONIC_CLOCK	1
#define _ENUM__SC_MQ_OPEN_MAX	1
#define _ENUM__SC_MQ_PRIO_MAX	1
#define _ENUM__SC_MULTI_PROCESS	1
#define _ENUM__PC_NAME_MAX	1
#define _ENUM__SC_NETWORKING	1
#define _ENUM__SC_NGROUPS_MAX	1
#define _ENUM__SC_NL_ARGMAX	1
#define _ENUM__SC_NL_LANGMAX	1
#define _ENUM__SC_NL_MSGMAX	1
#define _ENUM__SC_NL_NMAX	1
#define _ENUM__SC_NL_SETMAX	1
#define _ENUM__SC_NL_TEXTMAX	1
#define _ENUM__PC_NO_TRUNC	1
#define _ENUM__SC_NPROCESSORS_CONF	1
#define _ENUM__SC_NPROCESSORS_ONLN	1
#define _ENUM__SC_NZERO	1
#define _ENUM__SC_OPEN_MAX	1
#define _ENUM__SC_PAGESIZE	1
#define _ENUM__SC_PASS_MAX	1
#define _ENUM__CS_PATH	1
#define _ENUM__PC_PATH_MAX	1
#define _ENUM__SC_2_PBS	1
#define _ENUM__SC_2_PBS_ACCOUNTING	1
#define _ENUM__SC_2_PBS_CHECKPOINT	1
#define _ENUM__SC_2_PBS_LOCATE	1
#define _ENUM__SC_2_PBS_MESSAGE	1
#define _ENUM__SC_2_PBS_TRACK	1
#define _ENUM__SC_PHYS_PAGES	1
#define _ENUM__SC_PII	1
#define _ENUM__SC_PII_INTERNET	1
#define _ENUM__SC_PII_INTERNET_DGRAM	1
#define _ENUM__SC_PII_INTERNET_STREAM	1
#define _ENUM__SC_PII_OSI	1
#define _ENUM__SC_PII_OSI_CLTS	1
#define _ENUM__SC_PII_OSI_COTS	1
#define _ENUM__SC_PII_OSI_M	1
#define _ENUM__SC_PII_SOCKET	1
#define _ENUM__SC_PII_XTI	1
#define _ENUM__SC_PIPE	1
#define _ENUM__PC_PIPE_BUF	1
#define _ENUM__SC_POLL	1
#define _ENUM__SC_PRIORITIZED_IO	1
#define _ENUM__SC_PRIORITY_SCHEDULING	1
#define _ENUM__PC_PRIO_IO	1
#define _ENUM__SC_RAW_SOCKETS	1
#define _ENUM__SC_READER_WRITER_LOCKS	1
#define _ENUM__SC_XOPEN_REALTIME	1
#define _ENUM__SC_REALTIME_SIGNALS	1
#define _ENUM__SC_XOPEN_REALTIME_THREADS	1
#define _ENUM__PC_REC_INCR_XFER_SIZE	1
#define _ENUM__PC_REC_MAX_XFER_SIZE	1
#define _ENUM__PC_REC_MIN_XFER_SIZE	1
#define _ENUM__PC_REC_XFER_ALIGN	1
#define _ENUM__SC_REGEXP	1
#define _ENUM__SC_REGEX_VERSION	1
#define _ENUM__SC_RE_DUP_MAX	1
#define _ENUM__SC_RTSIG_MAX	1
#define _ENUM__SC_SAVED_IDS	1
#define _ENUM__SC_SCHAR_MAX	1
#define _ENUM__SC_SCHAR_MIN	1
#define _ENUM__SC_SELECT	1
#define _ENUM__SC_SEMAPHORES	1
#define _ENUM__SC_SEM_NSEMS_MAX	1
#define _ENUM__SC_SEM_VALUE_MAX	1
#define _ENUM__SC_SHARED_MEMORY_OBJECTS	1
#define _ENUM__SC_SHELL	1
#define _ENUM__SC_XOPEN_SHM	1
#define _ENUM__SC_SHRT_MAX	1
#define _ENUM__SC_SHRT_MIN	1
#define _ENUM__SC_SIGNALS	1
#define _ENUM__SC_SIGQUEUE_MAX	1
#define _ENUM__SC_SINGLE_PROCESS	1
#define _ENUM__PC_SOCK_MAXBUF	1
#define _ENUM__SC_SPAWN	1
#define _ENUM__SC_SPIN_LOCKS	1
#define _ENUM__SC_SPORADIC_SERVER	1
#define _ENUM__SC_SSIZE_MAX	1
#define _ENUM__SC_STREAMS	1
#define _ENUM__SC_STREAM_MAX	1
#define _ENUM__SC_2_SW_DEV	1
#define _ENUM__PC_2_SYMLINKS	1
#define _ENUM__PC_SYMLINK_MAX	1
#define _ENUM__SC_SYMLOOP_MAX	1
#define _ENUM__SC_SYNCHRONIZED_IO	1
#define _ENUM__PC_SYNC_IO	1
#define _ENUM__SC_SYSTEM_DATABASE	1
#define _ENUM__SC_SYSTEM_DATABASE_R	1
#define _ENUM__SC_THREADS	1
#define _ENUM__SC_THREAD_ATTR_STACKADDR	1
#define _ENUM__SC_THREAD_ATTR_STACKSIZE	1
#define _ENUM__SC_THREAD_CPUTIME	1
#define _ENUM__SC_THREAD_DESTRUCTOR_ITERATIONS	1
#define _ENUM__SC_THREAD_KEYS_MAX	1
#define _ENUM__SC_THREAD_PRIORITY_SCHEDULING	1
#define _ENUM__SC_THREAD_PRIO_INHERIT	1
#define _ENUM__SC_THREAD_PRIO_PROTECT	1
#define _ENUM__SC_THREAD_PROCESS_SHARED	1
#define _ENUM__SC_THREAD_SAFE_FUNCTIONS	1
#define _ENUM__SC_THREAD_SPORADIC_SERVER	1
#define _ENUM__SC_THREAD_STACK_MIN	1
#define _ENUM__SC_THREAD_THREADS_MAX	1
#define _ENUM__SC_TIMEOUTS	1
#define _ENUM__SC_TIMERS	1
#define _ENUM__SC_TIMER_MAX	1
#define _ENUM__SC_TRACE	1
#define _ENUM__SC_TRACE_EVENT_FILTER	1
#define _ENUM__SC_TRACE_INHERIT	1
#define _ENUM__SC_TRACE_LOG	1
#define _ENUM__SC_TTY_NAME_MAX	1
#define _ENUM__SC_TYPED_MEMORY_OBJECTS	1
#define _ENUM__SC_TZNAME_MAX	1
#define _ENUM__SC_T_IOV_MAX	1
#define _ENUM__SC_UCHAR_MAX	1
#define _ENUM__SC_UINT_MAX	1
#define _ENUM__SC_UIO_MAXIOV	1
#define _ENUM__SC_ULONG_MAX	1
#define _ENUM__SC_XOPEN_UNIX	1
#define _ENUM__SC_2_UPE	1
#define _ENUM__SC_USER_GROUPS	1
#define _ENUM__SC_USER_GROUPS_R	1
#define _ENUM__SC_USHRT_MAX	1
#define _ENUM__SC_V6_ILP32_OFF32	1
#define _ENUM__CS_POSIX_V6_ILP32_OFF32_CFLAGS	1
#define _ENUM__CS_POSIX_V6_ILP32_OFF32_LDFLAGS	1
#define _ENUM__CS_POSIX_V6_ILP32_OFF32_LIBS	1
#define _ENUM__CS_POSIX_V6_ILP32_OFF32_LINTFLAGS	1
#define _ENUM__SC_V6_ILP32_OFFBIG	1
#define _ENUM__CS_POSIX_V6_ILP32_OFFBIG_CFLAGS	1
#define _ENUM__CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS	1
#define _ENUM__CS_POSIX_V6_ILP32_OFFBIG_LIBS	1
#define _ENUM__CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS	1
#define _ENUM__SC_V6_LP64_OFF64	1
#define _ENUM__CS_POSIX_V6_LP64_OFF64_CFLAGS	1
#define _ENUM__CS_POSIX_V6_LP64_OFF64_LDFLAGS	1
#define _ENUM__CS_POSIX_V6_LP64_OFF64_LIBS	1
#define _ENUM__CS_POSIX_V6_LP64_OFF64_LINTFLAGS	1
#define _ENUM__SC_V6_LPBIG_OFFBIG	1
#define _ENUM__CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS	1
#define _ENUM__CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS	1
#define _ENUM__CS_POSIX_V6_LPBIG_OFFBIG_LIBS	1
#define _ENUM__CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS	1
#define _ENUM__CS_V6_WIDTH_RESTRICTED_ENVS	1
#define _ENUM__PC_VDISABLE	1
#define _ENUM__SC_VERSION	1
#define _ENUM__SC_2_VERSION	1
#define _ENUM__SC_XOPEN_VERSION	1
#define _ENUM__SC_WORD_BIT	1
#define _ENUM__SC_XOPEN_XCU_VERSION	1
#define _ENUM__SC_XOPEN_XPG2	1
#define _ENUM__SC_XOPEN_XPG3	1
#define _ENUM__SC_XOPEN_XPG4	1

/*
 * internal to external conf index map
 */

const short confmap[] =
{
	598,
#if	defined(_SC_AIO_LISTIO_MAX) || _ENUM__SC_AIO_LISTIO_MAX
	_SC_AIO_LISTIO_MAX,
#else
	-1,
#endif
#if	defined(_SC_AIO_MAX) || _ENUM__SC_AIO_MAX
	_SC_AIO_MAX,
#else
	-1,
#endif
#if	defined(_SC_AIO_PRIO_DELTA_MAX) || _ENUM__SC_AIO_PRIO_DELTA_MAX
	_SC_AIO_PRIO_DELTA_MAX,
#else
	-1,
#endif
#if	defined(_SC_ARG_MAX) || _ENUM__SC_ARG_MAX
	_SC_ARG_MAX,
#else
	-1,
#endif
#if	defined(_SC_ASYNCHRONOUS_IO) || _ENUM__SC_ASYNCHRONOUS_IO
	_SC_ASYNCHRONOUS_IO,
#else
	-1,
#endif
#if	defined(_PC_ASYNC_IO) || _ENUM__PC_ASYNC_IO
	_PC_ASYNC_IO,
#else
	-1,
#endif
#if	defined(_SC_BC_BASE_MAX) || _ENUM__SC_BC_BASE_MAX
	_SC_BC_BASE_MAX,
#else
	-1,
#endif
#if	defined(_SC_BC_DIM_MAX) || _ENUM__SC_BC_DIM_MAX
	_SC_BC_DIM_MAX,
#else
	-1,
#endif
#if	defined(_SC_BC_SCALE_MAX) || _ENUM__SC_BC_SCALE_MAX
	_SC_BC_SCALE_MAX,
#else
	-1,
#endif
#if	defined(_SC_BC_STRING_MAX) || _ENUM__SC_BC_STRING_MAX
	_SC_BC_STRING_MAX,
#else
	-1,
#endif
#if	defined(_SC_2_C_BIND) || _ENUM__SC_2_C_BIND
	_SC_2_C_BIND,
#else
	-1,
#endif
#if	defined(_SC_2_C_DEV) || _ENUM__SC_2_C_DEV
	_SC_2_C_DEV,
#else
	-1,
#endif
	-1,
	-1,
	-1,
#if	defined(_SC_2_CHAR_TERM) || _ENUM__SC_2_CHAR_TERM
	_SC_2_CHAR_TERM,
#else
	-1,
#endif
#if	defined(_SC_CHILD_MAX) || _ENUM__SC_CHILD_MAX
	_SC_CHILD_MAX,
#else
	-1,
#endif
#if	defined(_PC_CHOWN_RESTRICTED) || _ENUM__PC_CHOWN_RESTRICTED
	_PC_CHOWN_RESTRICTED,
#else
	-1,
#endif
#if	defined(_SC_CLK_TCK) || _ENUM__SC_CLK_TCK
	_SC_CLK_TCK,
#else
	-1,
#endif
#if	defined(_SC_CLOCKRES_MIN) || _ENUM__SC_CLOCKRES_MIN
	_SC_CLOCKRES_MIN,
#else
	-1,
#endif
#if	defined(_SC_COLL_WEIGHTS_MAX) || _ENUM__SC_COLL_WEIGHTS_MAX
	_SC_COLL_WEIGHTS_MAX,
#else
	-1,
#endif
#if	defined(_SC_DELAYTIMER_MAX) || _ENUM__SC_DELAYTIMER_MAX
	_SC_DELAYTIMER_MAX,
#else
	-1,
#endif
#if	defined(_SC_EXPR_NEST_MAX) || _ENUM__SC_EXPR_NEST_MAX
	_SC_EXPR_NEST_MAX,
#else
	-1,
#endif
#if	defined(_SC_FCHR_MAX) || _ENUM__SC_FCHR_MAX
	_SC_FCHR_MAX,
#else
	-1,
#endif
#if	defined(_SC_2_FORT_DEV) || _ENUM__SC_2_FORT_DEV
	_SC_2_FORT_DEV,
#else
	-1,
#endif
#if	defined(_SC_2_FORT_RUN) || _ENUM__SC_2_FORT_RUN
	_SC_2_FORT_RUN,
#else
	-1,
#endif
#if	defined(_SC_FSYNC) || _ENUM__SC_FSYNC
	_SC_FSYNC,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_JOB_CONTROL) || _ENUM__SC_JOB_CONTROL
	_SC_JOB_CONTROL,
#else
	-1,
#endif
#if	defined(_SC_LINE_MAX) || _ENUM__SC_LINE_MAX
	_SC_LINE_MAX,
#else
	-1,
#endif
#if	defined(_PC_LINK_MAX) || _ENUM__PC_LINK_MAX
	_PC_LINK_MAX,
#else
	-1,
#endif
#if	defined(_SC_2_LOCALEDEF) || _ENUM__SC_2_LOCALEDEF
	_SC_2_LOCALEDEF,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_MAPPED_FILES) || _ENUM__SC_MAPPED_FILES
	_SC_MAPPED_FILES,
#else
	-1,
#endif
#if	defined(_PC_MAX_CANON) || _ENUM__PC_MAX_CANON
	_PC_MAX_CANON,
#else
	-1,
#endif
#if	defined(_PC_MAX_INPUT) || _ENUM__PC_MAX_INPUT
	_PC_MAX_INPUT,
#else
	-1,
#endif
	-1,
#if	defined(_SC_MEMLOCK) || _ENUM__SC_MEMLOCK
	_SC_MEMLOCK,
#else
	-1,
#endif
#if	defined(_SC_MEMLOCK_RANGE) || _ENUM__SC_MEMLOCK_RANGE
	_SC_MEMLOCK_RANGE,
#else
	-1,
#endif
#if	defined(_SC_MEMORY_PROTECTION) || _ENUM__SC_MEMORY_PROTECTION
	_SC_MEMORY_PROTECTION,
#else
	-1,
#endif
#if	defined(_SC_MESSAGE_PASSING) || _ENUM__SC_MESSAGE_PASSING
	_SC_MESSAGE_PASSING,
#else
	-1,
#endif
#if	defined(_SC_MQ_OPEN_MAX) || _ENUM__SC_MQ_OPEN_MAX
	_SC_MQ_OPEN_MAX,
#else
	-1,
#endif
#if	defined(_SC_MQ_PRIO_MAX) || _ENUM__SC_MQ_PRIO_MAX
	_SC_MQ_PRIO_MAX,
#else
	-1,
#endif
#if	defined(_PC_NAME_MAX) || _ENUM__PC_NAME_MAX
	_PC_NAME_MAX,
#else
	-1,
#endif
#if	defined(_SC_NGROUPS_MAX) || _ENUM__SC_NGROUPS_MAX
	_SC_NGROUPS_MAX,
#else
	-1,
#endif
#if	defined(_PC_NO_TRUNC) || _ENUM__PC_NO_TRUNC
	_PC_NO_TRUNC,
#else
	-1,
#endif
#if	defined(_SC_OPEN_MAX) || _ENUM__SC_OPEN_MAX
	_SC_OPEN_MAX,
#else
	-1,
#endif
	-1,
#if	defined(_SC_PAGESIZE) || _ENUM__SC_PAGESIZE
	_SC_PAGESIZE,
#else
	-1,
#endif
#if	defined(_CS_PATH) || _ENUM__CS_PATH
	_CS_PATH,
#else
	-1,
#endif
#if	defined(_PC_PATH_MAX) || _ENUM__PC_PATH_MAX
	_PC_PATH_MAX,
#else
	-1,
#endif
#if	defined(_SC_PID_MAX) || _ENUM__SC_PID_MAX
	_SC_PID_MAX,
#else
	-1,
#endif
#if	defined(_PC_PIPE_BUF) || _ENUM__PC_PIPE_BUF
	_PC_PIPE_BUF,
#else
	-1,
#endif
	-1,
#if	defined(_SC_PRIORITIZED_IO) || _ENUM__SC_PRIORITIZED_IO
	_SC_PRIORITIZED_IO,
#else
	-1,
#endif
#if	defined(_SC_PRIORITY_SCHEDULING) || _ENUM__SC_PRIORITY_SCHEDULING
	_SC_PRIORITY_SCHEDULING,
#else
	-1,
#endif
#if	defined(_PC_PRIO_IO) || _ENUM__PC_PRIO_IO
	_PC_PRIO_IO,
#else
	-1,
#endif
#if	defined(_SC_REALTIME_SIGNALS) || _ENUM__SC_REALTIME_SIGNALS
	_SC_REALTIME_SIGNALS,
#else
	-1,
#endif
#if	defined(_SC_RE_DUP_MAX) || _ENUM__SC_RE_DUP_MAX
	_SC_RE_DUP_MAX,
#else
	-1,
#endif
#if	defined(_SC_RTSIG_MAX) || _ENUM__SC_RTSIG_MAX
	_SC_RTSIG_MAX,
#else
	-1,
#endif
#if	defined(_SC_SAVED_IDS) || _ENUM__SC_SAVED_IDS
	_SC_SAVED_IDS,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_SEMAPHORES) || _ENUM__SC_SEMAPHORES
	_SC_SEMAPHORES,
#else
	-1,
#endif
#if	defined(_SC_SEM_NSEMS_MAX) || _ENUM__SC_SEM_NSEMS_MAX
	_SC_SEM_NSEMS_MAX,
#else
	-1,
#endif
#if	defined(_SC_SEM_VALUE_MAX) || _ENUM__SC_SEM_VALUE_MAX
	_SC_SEM_VALUE_MAX,
#else
	-1,
#endif
#if	defined(_SC_SHARED_MEMORY_OBJECTS) || _ENUM__SC_SHARED_MEMORY_OBJECTS
	_SC_SHARED_MEMORY_OBJECTS,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_SIGQUEUE_MAX) || _ENUM__SC_SIGQUEUE_MAX
	_SC_SIGQUEUE_MAX,
#else
	-1,
#endif
	-1,
#if	defined(_SC_STD_BLK) || _ENUM__SC_STD_BLK
	_SC_STD_BLK,
#else
	-1,
#endif
#if	defined(_SC_STREAM_MAX) || _ENUM__SC_STREAM_MAX
	_SC_STREAM_MAX,
#else
	-1,
#endif
#if	defined(_SC_2_SW_DEV) || _ENUM__SC_2_SW_DEV
	_SC_2_SW_DEV,
#else
	-1,
#endif
#if	defined(_SC_SYNCHRONIZED_IO) || _ENUM__SC_SYNCHRONIZED_IO
	_SC_SYNCHRONIZED_IO,
#else
	-1,
#endif
#if	defined(_PC_SYNC_IO) || _ENUM__PC_SYNC_IO
	_PC_SYNC_IO,
#else
	-1,
#endif
#if	defined(_SC_SYSPID_MAX) || _ENUM__SC_SYSPID_MAX
	_SC_SYSPID_MAX,
#else
	-1,
#endif
#if	defined(_SC_TIMERS) || _ENUM__SC_TIMERS
	_SC_TIMERS,
#else
	-1,
#endif
#if	defined(_SC_TIMER_MAX) || _ENUM__SC_TIMER_MAX
	_SC_TIMER_MAX,
#else
	-1,
#endif
#if	defined(_SC_ATEXIT_MAX) || _ENUM__SC_ATEXIT_MAX
	_SC_ATEXIT_MAX,
#else
	-1,
#endif
#if	defined(_SC_TZNAME_MAX) || _ENUM__SC_TZNAME_MAX
	_SC_TZNAME_MAX,
#else
	-1,
#endif
	-1,
#if	defined(_SC_UID_MAX) || _ENUM__SC_UID_MAX
	_SC_UID_MAX,
#else
	-1,
#endif
	-1,
	-1,
	-1,
#if	defined(_SC_2_UPE) || _ENUM__SC_2_UPE
	_SC_2_UPE,
#else
	-1,
#endif
#if	defined(_PC_VDISABLE) || _ENUM__PC_VDISABLE
	_PC_VDISABLE,
#else
	-1,
#endif
#if	defined(_SC_VERSION) || _ENUM__SC_VERSION
	_SC_VERSION,
#else
	-1,
#endif
#if	defined(_SC_2_VERSION) || _ENUM__SC_2_VERSION
	_SC_2_VERSION,
#else
	-1,
#endif
#if	defined(_PC_SYMLINK_MAX) || _ENUM__PC_SYMLINK_MAX
	_PC_SYMLINK_MAX,
#else
	-1,
#endif
#if	defined(_SC_SYMLOOP_MAX) || _ENUM__SC_SYMLOOP_MAX
	_SC_SYMLOOP_MAX,
#else
	-1,
#endif
#if	defined(_SC_REGEXP) || _ENUM__SC_REGEXP
	_SC_REGEXP,
#else
	-1,
#endif
#if	defined(_SC_RESOURCE_LIMITS) || _ENUM__SC_RESOURCE_LIMITS
	_SC_RESOURCE_LIMITS,
#else
	-1,
#endif
#if	defined(_SC_CKPT) || _ENUM__SC_CKPT
	_SC_CKPT,
#else
	-1,
#endif
#if	defined(_SC_2_C_VERSION) || _ENUM__SC_2_C_VERSION
	_SC_2_C_VERSION,
#else
	-1,
#endif
	-1,
#if	defined(_SC_IOV_MAX) || _ENUM__SC_IOV_MAX
	_SC_IOV_MAX,
#else
	-1,
#endif
#if	defined(_SC_PAGE_SIZE) || _ENUM__SC_PAGE_SIZE
	_SC_PAGE_SIZE,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_XOPEN_VERSION) || _ENUM__SC_XOPEN_VERSION
	_SC_XOPEN_VERSION,
#else
	-1,
#endif
#if	defined(_SC_XOPEN_XCU_VERSION) || _ENUM__SC_XOPEN_XCU_VERSION
	_SC_XOPEN_XCU_VERSION,
#else
	-1,
#endif
	-1,
	-1,
	-1,
#if	defined(_SC_XOPEN_UNIX) || _ENUM__SC_XOPEN_UNIX
	_SC_XOPEN_UNIX,
#else
	-1,
#endif
#if	defined(_SC_XOPEN_CRYPT) || _ENUM__SC_XOPEN_CRYPT
	_SC_XOPEN_CRYPT,
#else
	-1,
#endif
#if	defined(_SC_XOPEN_ENH_I18N) || _ENUM__SC_XOPEN_ENH_I18N
	_SC_XOPEN_ENH_I18N,
#else
	-1,
#endif
#if	defined(_SC_XOPEN_SHM) || _ENUM__SC_XOPEN_SHM
	_SC_XOPEN_SHM,
#else
	-1,
#endif
#if	defined(_SC_AES_OS_VERSION) || _ENUM__SC_AES_OS_VERSION
	_SC_AES_OS_VERSION,
#else
	-1,
#endif
#if	defined(_CS_SHELL) || _ENUM__CS_SHELL
	_CS_SHELL,
#else
	-1,
#endif
#if	defined(_SC_AVPHYS_PAGES) || _ENUM__SC_AVPHYS_PAGES
	_SC_AVPHYS_PAGES,
#else
	-1,
#endif
#if	defined(_SC_NACLS_MAX) || _ENUM__SC_NACLS_MAX
	_SC_NACLS_MAX,
#else
	-1,
#endif
#if	defined(_SC_NPROCESSORS_CONF) || _ENUM__SC_NPROCESSORS_CONF
	_SC_NPROCESSORS_CONF,
#else
	-1,
#endif
#if	defined(_SC_NPROCESSORS_ONLN) || _ENUM__SC_NPROCESSORS_ONLN
	_SC_NPROCESSORS_ONLN,
#else
	-1,
#endif
#if	defined(_SC_PHYS_PAGES) || _ENUM__SC_PHYS_PAGES
	_SC_PHYS_PAGES,
#else
	-1,
#endif
#if	defined(_SC_SIGRT_MAX) || _ENUM__SC_SIGRT_MAX
	_SC_SIGRT_MAX,
#else
	-1,
#endif
#if	defined(_SC_SIGRT_MIN) || _ENUM__SC_SIGRT_MIN
	_SC_SIGRT_MIN,
#else
	-1,
#endif
#if	defined(_SC_TMP_MAX) || _ENUM__SC_TMP_MAX
	_SC_TMP_MAX,
#else
	-1,
#endif
#if	defined(_SC_LOGNAME_MAX) || _ENUM__SC_LOGNAME_MAX
	_SC_LOGNAME_MAX,
#else
	-1,
#endif
#if	defined(_SC_PASS_MAX) || _ENUM__SC_PASS_MAX
	_SC_PASS_MAX,
#else
	-1,
#endif
#if	defined(_CS_TMP) || _ENUM__CS_TMP
	_CS_TMP,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_CLIST) || _ENUM__SC_KERNEL_CLIST
	_SC_KERNEL_CLIST,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_CLIST_MAX) || _ENUM__SC_KERNEL_CLIST_MAX
	_SC_KERNEL_CLIST_MAX,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_DISK) || _ENUM__SC_KERNEL_DISK
	_SC_KERNEL_DISK,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_DISK_MAX) || _ENUM__SC_KERNEL_DISK_MAX
	_SC_KERNEL_DISK_MAX,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_DMABUF) || _ENUM__SC_KERNEL_DMABUF
	_SC_KERNEL_DMABUF,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_DMABUF_MAX) || _ENUM__SC_KERNEL_DMABUF_MAX
	_SC_KERNEL_DMABUF_MAX,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_FILE) || _ENUM__SC_KERNEL_FILE
	_SC_KERNEL_FILE,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_FILE_MAX) || _ENUM__SC_KERNEL_FILE_MAX
	_SC_KERNEL_FILE_MAX,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_FLCKREC) || _ENUM__SC_KERNEL_FLCKREC
	_SC_KERNEL_FLCKREC,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_FLCKREC_MAX) || _ENUM__SC_KERNEL_FLCKREC_MAX
	_SC_KERNEL_FLCKREC_MAX,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_INODE) || _ENUM__SC_KERNEL_INODE
	_SC_KERNEL_INODE,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_INODE_MAX) || _ENUM__SC_KERNEL_INODE_MAX
	_SC_KERNEL_INODE_MAX,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_MOUNT) || _ENUM__SC_KERNEL_MOUNT
	_SC_KERNEL_MOUNT,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_MOUNT_MAX) || _ENUM__SC_KERNEL_MOUNT_MAX
	_SC_KERNEL_MOUNT_MAX,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_PINODE) || _ENUM__SC_KERNEL_PINODE
	_SC_KERNEL_PINODE,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_PINODE_MAX) || _ENUM__SC_KERNEL_PINODE_MAX
	_SC_KERNEL_PINODE_MAX,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_PROC) || _ENUM__SC_KERNEL_PROC
	_SC_KERNEL_PROC,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_PROC_MAX) || _ENUM__SC_KERNEL_PROC_MAX
	_SC_KERNEL_PROC_MAX,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_REGION) || _ENUM__SC_KERNEL_REGION
	_SC_KERNEL_REGION,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_REGION_MAX) || _ENUM__SC_KERNEL_REGION_MAX
	_SC_KERNEL_REGION_MAX,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_S5INODE) || _ENUM__SC_KERNEL_S5INODE
	_SC_KERNEL_S5INODE,
#else
	-1,
#endif
#if	defined(_SC_KERNEL_S5INODE_MAX) || _ENUM__SC_KERNEL_S5INODE_MAX
	_SC_KERNEL_S5INODE_MAX,
#else
	-1,
#endif
#if	defined(_PC_FILESIZEBITS) || _ENUM__PC_FILESIZEBITS
	_PC_FILESIZEBITS,
#else
	-1,
#endif
#if	defined(_CS_LFS_CFLAGS) || _ENUM__CS_LFS_CFLAGS
	_CS_LFS_CFLAGS,
#else
	-1,
#endif
#if	defined(_CS_LFS_LDFLAGS) || _ENUM__CS_LFS_LDFLAGS
	_CS_LFS_LDFLAGS,
#else
	-1,
#endif
#if	defined(_CS_LFS_LINTFLAGS) || _ENUM__CS_LFS_LINTFLAGS
	_CS_LFS_LINTFLAGS,
#else
	-1,
#endif
#if	defined(_CS_LFS_LIBS) || _ENUM__CS_LFS_LIBS
	_CS_LFS_LIBS,
#else
	-1,
#endif
#if	defined(_CS_LFS64_CFLAGS) || _ENUM__CS_LFS64_CFLAGS
	_CS_LFS64_CFLAGS,
#else
	-1,
#endif
#if	defined(_CS_LFS64_LDFLAGS) || _ENUM__CS_LFS64_LDFLAGS
	_CS_LFS64_LDFLAGS,
#else
	-1,
#endif
#if	defined(_CS_LFS64_LINTFLAGS) || _ENUM__CS_LFS64_LINTFLAGS
	_CS_LFS64_LINTFLAGS,
#else
	-1,
#endif
#if	defined(_CS_LFS64_LIBS) || _ENUM__CS_LFS64_LIBS
	_CS_LFS64_LIBS,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_EQUIV_CLASS_MAX) || _ENUM__SC_EQUIV_CLASS_MAX
	_SC_EQUIV_CLASS_MAX,
#else
	-1,
#endif
	-1,
#if	defined(_SC_GETGR_R_SIZE_MAX) || _ENUM__SC_GETGR_R_SIZE_MAX
	_SC_GETGR_R_SIZE_MAX,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_XBS5_ILP32_OFF32) || _ENUM__SC_XBS5_ILP32_OFF32
	_SC_XBS5_ILP32_OFF32,
#else
	-1,
#endif
#if	defined(_CS_XBS5_ILP32_OFF32_CFLAGS) || _ENUM__CS_XBS5_ILP32_OFF32_CFLAGS
	_CS_XBS5_ILP32_OFF32_CFLAGS,
#else
	-1,
#endif
#if	defined(_CS_XBS5_ILP32_OFF32_LDFLAGS) || _ENUM__CS_XBS5_ILP32_OFF32_LDFLAGS
	_CS_XBS5_ILP32_OFF32_LDFLAGS,
#else
	-1,
#endif
#if	defined(_CS_XBS5_ILP32_OFF32_LIBS) || _ENUM__CS_XBS5_ILP32_OFF32_LIBS
	_CS_XBS5_ILP32_OFF32_LIBS,
#else
	-1,
#endif
#if	defined(_CS_XBS5_ILP32_OFF32_LINTFLAGS) || _ENUM__CS_XBS5_ILP32_OFF32_LINTFLAGS
	_CS_XBS5_ILP32_OFF32_LINTFLAGS,
#else
	-1,
#endif
#if	defined(_SC_XBS5_ILP32_OFFBIG) || _ENUM__SC_XBS5_ILP32_OFFBIG
	_SC_XBS5_ILP32_OFFBIG,
#else
	-1,
#endif
#if	defined(_CS_XBS5_ILP32_OFFBIG_CFLAGS) || _ENUM__CS_XBS5_ILP32_OFFBIG_CFLAGS
	_CS_XBS5_ILP32_OFFBIG_CFLAGS,
#else
	-1,
#endif
#if	defined(_CS_XBS5_ILP32_OFFBIG_LDFLAGS) || _ENUM__CS_XBS5_ILP32_OFFBIG_LDFLAGS
	_CS_XBS5_ILP32_OFFBIG_LDFLAGS,
#else
	-1,
#endif
#if	defined(_CS_XBS5_ILP32_OFFBIG_LIBS) || _ENUM__CS_XBS5_ILP32_OFFBIG_LIBS
	_CS_XBS5_ILP32_OFFBIG_LIBS,
#else
	-1,
#endif
#if	defined(_CS_XBS5_ILP32_OFFBIG_LINTFLAGS) || _ENUM__CS_XBS5_ILP32_OFFBIG_LINTFLAGS
	_CS_XBS5_ILP32_OFFBIG_LINTFLAGS,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_XOPEN_LEGACY) || _ENUM__SC_XOPEN_LEGACY
	_SC_XOPEN_LEGACY,
#else
	-1,
#endif
#if	defined(_SC_LOGIN_NAME_MAX) || _ENUM__SC_LOGIN_NAME_MAX
	_SC_LOGIN_NAME_MAX,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_XBS5_LP64_OFF64) || _ENUM__SC_XBS5_LP64_OFF64
	_SC_XBS5_LP64_OFF64,
#else
	-1,
#endif
#if	defined(_CS_XBS5_LP64_OFF64_CFLAGS) || _ENUM__CS_XBS5_LP64_OFF64_CFLAGS
	_CS_XBS5_LP64_OFF64_CFLAGS,
#else
	-1,
#endif
#if	defined(_CS_XBS5_LP64_OFF64_LDFLAGS) || _ENUM__CS_XBS5_LP64_OFF64_LDFLAGS
	_CS_XBS5_LP64_OFF64_LDFLAGS,
#else
	-1,
#endif
#if	defined(_CS_XBS5_LP64_OFF64_LIBS) || _ENUM__CS_XBS5_LP64_OFF64_LIBS
	_CS_XBS5_LP64_OFF64_LIBS,
#else
	-1,
#endif
#if	defined(_CS_XBS5_LP64_OFF64_LINTFLAGS) || _ENUM__CS_XBS5_LP64_OFF64_LINTFLAGS
	_CS_XBS5_LP64_OFF64_LINTFLAGS,
#else
	-1,
#endif
#if	defined(_SC_XBS5_LPBIG_OFFBIG) || _ENUM__SC_XBS5_LPBIG_OFFBIG
	_SC_XBS5_LPBIG_OFFBIG,
#else
	-1,
#endif
#if	defined(_CS_XBS5_LPBIG_OFFBIG_CFLAGS) || _ENUM__CS_XBS5_LPBIG_OFFBIG_CFLAGS
	_CS_XBS5_LPBIG_OFFBIG_CFLAGS,
#else
	-1,
#endif
#if	defined(_CS_XBS5_LPBIG_OFFBIG_LDFLAGS) || _ENUM__CS_XBS5_LPBIG_OFFBIG_LDFLAGS
	_CS_XBS5_LPBIG_OFFBIG_LDFLAGS,
#else
	-1,
#endif
#if	defined(_CS_XBS5_LPBIG_OFFBIG_LIBS) || _ENUM__CS_XBS5_LPBIG_OFFBIG_LIBS
	_CS_XBS5_LPBIG_OFFBIG_LIBS,
#else
	-1,
#endif
#if	defined(_CS_XBS5_LPBIG_OFFBIG_LINTFLAGS) || _ENUM__CS_XBS5_LPBIG_OFFBIG_LINTFLAGS
	_CS_XBS5_LPBIG_OFFBIG_LINTFLAGS,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_PII) || _ENUM__SC_PII
	_SC_PII,
#else
	-1,
#endif
#if	defined(_SC_PII_INTERNET) || _ENUM__SC_PII_INTERNET
	_SC_PII_INTERNET,
#else
	-1,
#endif
#if	defined(_SC_PII_INTERNET_DGRAM) || _ENUM__SC_PII_INTERNET_DGRAM
	_SC_PII_INTERNET_DGRAM,
#else
	-1,
#endif
#if	defined(_SC_PII_INTERNET_STREAM) || _ENUM__SC_PII_INTERNET_STREAM
	_SC_PII_INTERNET_STREAM,
#else
	-1,
#endif
#if	defined(_SC_PII_OSI) || _ENUM__SC_PII_OSI
	_SC_PII_OSI,
#else
	-1,
#endif
#if	defined(_SC_PII_OSI_CLTS) || _ENUM__SC_PII_OSI_CLTS
	_SC_PII_OSI_CLTS,
#else
	-1,
#endif
#if	defined(_SC_PII_OSI_COTS) || _ENUM__SC_PII_OSI_COTS
	_SC_PII_OSI_COTS,
#else
	-1,
#endif
#if	defined(_SC_PII_OSI_M) || _ENUM__SC_PII_OSI_M
	_SC_PII_OSI_M,
#else
	-1,
#endif
#if	defined(_SC_PII_SOCKET) || _ENUM__SC_PII_SOCKET
	_SC_PII_SOCKET,
#else
	-1,
#endif
#if	defined(_SC_PII_XTI) || _ENUM__SC_PII_XTI
	_SC_PII_XTI,
#else
	-1,
#endif
#if	defined(_SC_POLL) || _ENUM__SC_POLL
	_SC_POLL,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_XOPEN_REALTIME) || _ENUM__SC_XOPEN_REALTIME
	_SC_XOPEN_REALTIME,
#else
	-1,
#endif
#if	defined(_SC_XOPEN_REALTIME_THREADS) || _ENUM__SC_XOPEN_REALTIME_THREADS
	_SC_XOPEN_REALTIME_THREADS,
#else
	-1,
#endif
#if	defined(_SC_REENTRANT_FUNCTIONS) || _ENUM__SC_REENTRANT_FUNCTIONS
	_SC_REENTRANT_FUNCTIONS,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_SELECT) || _ENUM__SC_SELECT
	_SC_SELECT,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_PC_SOCK_MAXBUF) || _ENUM__PC_SOCK_MAXBUF
	_PC_SOCK_MAXBUF,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_THREADS) || _ENUM__SC_THREADS
	_SC_THREADS,
#else
	-1,
#endif
#if	defined(_SC_THREADS_PRIO_CEILING) || _ENUM__SC_THREADS_PRIO_CEILING
	_SC_THREADS_PRIO_CEILING,
#else
	-1,
#endif
#if	defined(_SC_THREADS_PRIO_INHERIT) || _ENUM__SC_THREADS_PRIO_INHERIT
	_SC_THREADS_PRIO_INHERIT,
#else
	-1,
#endif
#if	defined(_SC_THREAD_ATTR_STACKADDR) || _ENUM__SC_THREAD_ATTR_STACKADDR
	_SC_THREAD_ATTR_STACKADDR,
#else
	-1,
#endif
#if	defined(_SC_THREAD_ATTR_STACKSIZE) || _ENUM__SC_THREAD_ATTR_STACKSIZE
	_SC_THREAD_ATTR_STACKSIZE,
#else
	-1,
#endif
#if	defined(_SC_THREAD_DESTRUCTOR_ITERATIONS) || _ENUM__SC_THREAD_DESTRUCTOR_ITERATIONS
	_SC_THREAD_DESTRUCTOR_ITERATIONS,
#else
	-1,
#endif
#if	defined(_SC_THREAD_KEYS_MAX) || _ENUM__SC_THREAD_KEYS_MAX
	_SC_THREAD_KEYS_MAX,
#else
	-1,
#endif
#if	defined(_SC_THREAD_PRIORITY_SCHEDULING) || _ENUM__SC_THREAD_PRIORITY_SCHEDULING
	_SC_THREAD_PRIORITY_SCHEDULING,
#else
	-1,
#endif
#if	defined(_SC_THREAD_PRIO_INHERIT) || _ENUM__SC_THREAD_PRIO_INHERIT
	_SC_THREAD_PRIO_INHERIT,
#else
	-1,
#endif
#if	defined(_SC_THREAD_PRIO_PROTECT) || _ENUM__SC_THREAD_PRIO_PROTECT
	_SC_THREAD_PRIO_PROTECT,
#else
	-1,
#endif
#if	defined(_SC_THREAD_PROCESS_SHARED) || _ENUM__SC_THREAD_PROCESS_SHARED
	_SC_THREAD_PROCESS_SHARED,
#else
	-1,
#endif
#if	defined(_SC_THREAD_SAFE_FUNCTIONS) || _ENUM__SC_THREAD_SAFE_FUNCTIONS
	_SC_THREAD_SAFE_FUNCTIONS,
#else
	-1,
#endif
#if	defined(_SC_THREAD_STACK_MIN) || _ENUM__SC_THREAD_STACK_MIN
	_SC_THREAD_STACK_MIN,
#else
	-1,
#endif
#if	defined(_SC_THREAD_THREADS_MAX) || _ENUM__SC_THREAD_THREADS_MAX
	_SC_THREAD_THREADS_MAX,
#else
	-1,
#endif
#if	defined(_SC_TTY_NAME_MAX) || _ENUM__SC_TTY_NAME_MAX
	_SC_TTY_NAME_MAX,
#else
	-1,
#endif
#if	defined(_SC_T_IOV_MAX) || _ENUM__SC_T_IOV_MAX
	_SC_T_IOV_MAX,
#else
	-1,
#endif
	-1,
#if	defined(_SC_UIO_MAXIOV) || _ENUM__SC_UIO_MAXIOV
	_SC_UIO_MAXIOV,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_3_VERSION) || _ENUM__SC_3_VERSION
	_SC_3_VERSION,
#else
	-1,
#endif
#if	defined(_SC_4_VERSION) || _ENUM__SC_4_VERSION
	_SC_4_VERSION,
#else
	-1,
#endif
#if	defined(_SC_VERSION_88) || _ENUM__SC_VERSION_88
	_SC_VERSION_88,
#else
	-1,
#endif
	-1,
#if	defined(_SC_VERSION_90) || _ENUM__SC_VERSION_90
	_SC_VERSION_90,
#else
	-1,
#endif
	-1,
#if	defined(_SC_VERSION_93) || _ENUM__SC_VERSION_93
	_SC_VERSION_93,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_GETPW_R_SIZE_MAX) || _ENUM__SC_GETPW_R_SIZE_MAX
	_SC_GETPW_R_SIZE_MAX,
#else
	-1,
#endif
#if	defined(_SI_ARCHITECTURE) || _ENUM__SI_ARCHITECTURE
	_SI_ARCHITECTURE,
#else
	-1,
#endif
#if	defined(_SI_BUSTYPES) || _ENUM__SI_BUSTYPES
	_SI_BUSTYPES,
#else
	-1,
#endif
#if	defined(_SI_HOSTNAME) || _ENUM__SI_HOSTNAME
	_SI_HOSTNAME,
#else
	-1,
#endif
#if	defined(_SI_HW_PROVIDER) || _ENUM__SI_HW_PROVIDER
	_SI_HW_PROVIDER,
#else
	-1,
#endif
#if	defined(_SI_HW_SERIAL) || _ENUM__SI_HW_SERIAL
	_SI_HW_SERIAL,
#else
	-1,
#endif
#if	defined(_SI_INITTAB_NAME) || _ENUM__SI_INITTAB_NAME
	_SI_INITTAB_NAME,
#else
	-1,
#endif
#if	defined(_SI_KERNEL_STAMP) || _ENUM__SI_KERNEL_STAMP
	_SI_KERNEL_STAMP,
#else
	-1,
#endif
#if	defined(_SI_MACHINE) || _ENUM__SI_MACHINE
	_SI_MACHINE,
#else
	-1,
#endif
#if	defined(_SI_OS_BASE) || _ENUM__SI_OS_BASE
	_SI_OS_BASE,
#else
	-1,
#endif
#if	defined(_SI_OS_PROVIDER) || _ENUM__SI_OS_PROVIDER
	_SI_OS_PROVIDER,
#else
	-1,
#endif
#if	defined(_SI_RELEASE) || _ENUM__SI_RELEASE
	_SI_RELEASE,
#else
	-1,
#endif
#if	defined(_SI_SRPC_DOMAIN) || _ENUM__SI_SRPC_DOMAIN
	_SI_SRPC_DOMAIN,
#else
	-1,
#endif
#if	defined(_SI_SYSNAME) || _ENUM__SI_SYSNAME
	_SI_SYSNAME,
#else
	-1,
#endif
#if	defined(_SI_USER_LIMIT) || _ENUM__SI_USER_LIMIT
	_SI_USER_LIMIT,
#else
	-1,
#endif
#if	defined(_SI_VERSION) || _ENUM__SI_VERSION
	_SI_VERSION,
#else
	-1,
#endif
#if	defined(_SC_ADVISORY_INFO) || _ENUM__SC_ADVISORY_INFO
	_SC_ADVISORY_INFO,
#else
	-1,
#endif
#if	defined(_PC_ALLOC_SIZE_MIN) || _ENUM__PC_ALLOC_SIZE_MIN
	_PC_ALLOC_SIZE_MIN,
#else
	-1,
#endif
#if	defined(_SC_BARRIERS) || _ENUM__SC_BARRIERS
	_SC_BARRIERS,
#else
	-1,
#endif
#if	defined(_SC_CPUTIME) || _ENUM__SC_CPUTIME
	_SC_CPUTIME,
#else
	-1,
#endif
#if	defined(_SC_FILE_LOCKING) || _ENUM__SC_FILE_LOCKING
	_SC_FILE_LOCKING,
#else
	-1,
#endif
#if	defined(_SC_HOST_NAME_MAX) || _ENUM__SC_HOST_NAME_MAX
	_SC_HOST_NAME_MAX,
#else
	-1,
#endif
#if	defined(_SC_IPV6) || _ENUM__SC_IPV6
	_SC_IPV6,
#else
	-1,
#endif
#if	defined(_SC_MONOTONIC_CLOCK) || _ENUM__SC_MONOTONIC_CLOCK
	_SC_MONOTONIC_CLOCK,
#else
	-1,
#endif
#if	defined(_SC_MULTI_PROCESS) || _ENUM__SC_MULTI_PROCESS
	_SC_MULTI_PROCESS,
#else
	-1,
#endif
#if	defined(_SC_2_PBS) || _ENUM__SC_2_PBS
	_SC_2_PBS,
#else
	-1,
#endif
#if	defined(_SC_2_PBS_ACCOUNTING) || _ENUM__SC_2_PBS_ACCOUNTING
	_SC_2_PBS_ACCOUNTING,
#else
	-1,
#endif
#if	defined(_SC_2_PBS_CHECKPOINT) || _ENUM__SC_2_PBS_CHECKPOINT
	_SC_2_PBS_CHECKPOINT,
#else
	-1,
#endif
#if	defined(_SC_2_PBS_LOCATE) || _ENUM__SC_2_PBS_LOCATE
	_SC_2_PBS_LOCATE,
#else
	-1,
#endif
#if	defined(_SC_2_PBS_MESSAGE) || _ENUM__SC_2_PBS_MESSAGE
	_SC_2_PBS_MESSAGE,
#else
	-1,
#endif
#if	defined(_SC_2_PBS_TRACK) || _ENUM__SC_2_PBS_TRACK
	_SC_2_PBS_TRACK,
#else
	-1,
#endif
#if	defined(_SC_RAW_SOCKETS) || _ENUM__SC_RAW_SOCKETS
	_SC_RAW_SOCKETS,
#else
	-1,
#endif
#if	defined(_SC_READER_WRITER_LOCKS) || _ENUM__SC_READER_WRITER_LOCKS
	_SC_READER_WRITER_LOCKS,
#else
	-1,
#endif
#if	defined(_PC_REC_INCR_XFER_SIZE) || _ENUM__PC_REC_INCR_XFER_SIZE
	_PC_REC_INCR_XFER_SIZE,
#else
	-1,
#endif
#if	defined(_PC_REC_MIN_XFER_SIZE) || _ENUM__PC_REC_MIN_XFER_SIZE
	_PC_REC_MIN_XFER_SIZE,
#else
	-1,
#endif
#if	defined(_PC_REC_MAX_XFER_SIZE) || _ENUM__PC_REC_MAX_XFER_SIZE
	_PC_REC_MAX_XFER_SIZE,
#else
	-1,
#endif
#if	defined(_PC_REC_XFER_ALIGN) || _ENUM__PC_REC_XFER_ALIGN
	_PC_REC_XFER_ALIGN,
#else
	-1,
#endif
#if	defined(_SC_REGEX_VERSION) || _ENUM__SC_REGEX_VERSION
	_SC_REGEX_VERSION,
#else
	-1,
#endif
#if	defined(_SC_SPAWN) || _ENUM__SC_SPAWN
	_SC_SPAWN,
#else
	-1,
#endif
#if	defined(_SC_SPIN_LOCKS) || _ENUM__SC_SPIN_LOCKS
	_SC_SPIN_LOCKS,
#else
	-1,
#endif
#if	defined(_SC_SPORADIC_SERVER) || _ENUM__SC_SPORADIC_SERVER
	_SC_SPORADIC_SERVER,
#else
	-1,
#endif
#if	defined(_SC_THREAD_CPUTIME) || _ENUM__SC_THREAD_CPUTIME
	_SC_THREAD_CPUTIME,
#else
	-1,
#endif
#if	defined(_SC_THREAD_SPORADIC_SERVER) || _ENUM__SC_THREAD_SPORADIC_SERVER
	_SC_THREAD_SPORADIC_SERVER,
#else
	-1,
#endif
#if	defined(_SC_TIMEOUTS) || _ENUM__SC_TIMEOUTS
	_SC_TIMEOUTS,
#else
	-1,
#endif
#if	defined(_SC_TRACE) || _ENUM__SC_TRACE
	_SC_TRACE,
#else
	-1,
#endif
#if	defined(_SC_TRACE_EVENT_FILTER) || _ENUM__SC_TRACE_EVENT_FILTER
	_SC_TRACE_EVENT_FILTER,
#else
	-1,
#endif
#if	defined(_SC_TRACE_INHERIT) || _ENUM__SC_TRACE_INHERIT
	_SC_TRACE_INHERIT,
#else
	-1,
#endif
#if	defined(_SC_TRACE_LOG) || _ENUM__SC_TRACE_LOG
	_SC_TRACE_LOG,
#else
	-1,
#endif
#if	defined(_SC_TYPED_MEMORY_OBJECTS) || _ENUM__SC_TYPED_MEMORY_OBJECTS
	_SC_TYPED_MEMORY_OBJECTS,
#else
	-1,
#endif
#if	defined(_SC_V6_ILP32_OFF32) || _ENUM__SC_V6_ILP32_OFF32
	_SC_V6_ILP32_OFF32,
#else
	-1,
#endif
#if	defined(_SC_V6_ILP32_OFFBIG) || _ENUM__SC_V6_ILP32_OFFBIG
	_SC_V6_ILP32_OFFBIG,
#else
	-1,
#endif
#if	defined(_SC_V6_LP64_OFF64) || _ENUM__SC_V6_LP64_OFF64
	_SC_V6_LP64_OFF64,
#else
	-1,
#endif
#if	defined(_SC_V6_LPBIG_OFFBIG) || _ENUM__SC_V6_LPBIG_OFFBIG
	_SC_V6_LPBIG_OFFBIG,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_CS_GNU_LIBC_VERSION) || _ENUM__CS_GNU_LIBC_VERSION
	_CS_GNU_LIBC_VERSION,
#else
	-1,
#endif
#if	defined(_CS_GNU_LIBPTHREAD_VERSION) || _ENUM__CS_GNU_LIBPTHREAD_VERSION
	_CS_GNU_LIBPTHREAD_VERSION,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_CS_POSIX_V6_ILP32_OFF32_CFLAGS) || _ENUM__CS_POSIX_V6_ILP32_OFF32_CFLAGS
	_CS_POSIX_V6_ILP32_OFF32_CFLAGS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_ILP32_OFF32_LDFLAGS) || _ENUM__CS_POSIX_V6_ILP32_OFF32_LDFLAGS
	_CS_POSIX_V6_ILP32_OFF32_LDFLAGS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_ILP32_OFF32_LIBS) || _ENUM__CS_POSIX_V6_ILP32_OFF32_LIBS
	_CS_POSIX_V6_ILP32_OFF32_LIBS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS) || _ENUM__CS_POSIX_V6_ILP32_OFF32_LINTFLAGS
	_CS_POSIX_V6_ILP32_OFF32_LINTFLAGS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS) || _ENUM__CS_POSIX_V6_ILP32_OFFBIG_CFLAGS
	_CS_POSIX_V6_ILP32_OFFBIG_CFLAGS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS) || _ENUM__CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS
	_CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_ILP32_OFFBIG_LIBS) || _ENUM__CS_POSIX_V6_ILP32_OFFBIG_LIBS
	_CS_POSIX_V6_ILP32_OFFBIG_LIBS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS) || _ENUM__CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS
	_CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_LP64_OFF64_CFLAGS) || _ENUM__CS_POSIX_V6_LP64_OFF64_CFLAGS
	_CS_POSIX_V6_LP64_OFF64_CFLAGS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_LP64_OFF64_LDFLAGS) || _ENUM__CS_POSIX_V6_LP64_OFF64_LDFLAGS
	_CS_POSIX_V6_LP64_OFF64_LDFLAGS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_LP64_OFF64_LIBS) || _ENUM__CS_POSIX_V6_LP64_OFF64_LIBS
	_CS_POSIX_V6_LP64_OFF64_LIBS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_LP64_OFF64_LINTFLAGS) || _ENUM__CS_POSIX_V6_LP64_OFF64_LINTFLAGS
	_CS_POSIX_V6_LP64_OFF64_LINTFLAGS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS) || _ENUM__CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS
	_CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS) || _ENUM__CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS
	_CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_LPBIG_OFFBIG_LIBS) || _ENUM__CS_POSIX_V6_LPBIG_OFFBIG_LIBS
	_CS_POSIX_V6_LPBIG_OFFBIG_LIBS,
#else
	-1,
#endif
#if	defined(_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS) || _ENUM__CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS
	_CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS,
#else
	-1,
#endif
#if	defined(_CS_V6_WIDTH_RESTRICTED_ENVS) || _ENUM__CS_V6_WIDTH_RESTRICTED_ENVS
	_CS_V6_WIDTH_RESTRICTED_ENVS,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_PC_2_SYMLINKS) || _ENUM__PC_2_SYMLINKS
	_PC_2_SYMLINKS,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_BASE) || _ENUM__SC_BASE
	_SC_BASE,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_CHARCLASS_NAME_MAX) || _ENUM__SC_CHARCLASS_NAME_MAX
	_SC_CHARCLASS_NAME_MAX,
#else
	-1,
#endif
#if	defined(_SC_CHAR_BIT) || _ENUM__SC_CHAR_BIT
	_SC_CHAR_BIT,
#else
	-1,
#endif
#if	defined(_SC_CHAR_MAX) || _ENUM__SC_CHAR_MAX
	_SC_CHAR_MAX,
#else
	-1,
#endif
#if	defined(_SC_CHAR_MIN) || _ENUM__SC_CHAR_MIN
	_SC_CHAR_MIN,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_CLOCK_SELECTION) || _ENUM__SC_CLOCK_SELECTION
	_SC_CLOCK_SELECTION,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_C_LANG_SUPPORT) || _ENUM__SC_C_LANG_SUPPORT
	_SC_C_LANG_SUPPORT,
#else
	-1,
#endif
#if	defined(_SC_C_LANG_SUPPORT_R) || _ENUM__SC_C_LANG_SUPPORT_R
	_SC_C_LANG_SUPPORT_R,
#else
	-1,
#endif
	-1,
#if	defined(_SC_DEVICE_IO) || _ENUM__SC_DEVICE_IO
	_SC_DEVICE_IO,
#else
	-1,
#endif
#if	defined(_SC_DEVICE_SPECIFIC) || _ENUM__SC_DEVICE_SPECIFIC
	_SC_DEVICE_SPECIFIC,
#else
	-1,
#endif
#if	defined(_SC_DEVICE_SPECIFIC_R) || _ENUM__SC_DEVICE_SPECIFIC_R
	_SC_DEVICE_SPECIFIC_R,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_FD_MGMT) || _ENUM__SC_FD_MGMT
	_SC_FD_MGMT,
#else
	-1,
#endif
#if	defined(_SC_FIFO) || _ENUM__SC_FIFO
	_SC_FIFO,
#else
	-1,
#endif
#if	defined(_SC_FILE_ATTRIBUTES) || _ENUM__SC_FILE_ATTRIBUTES
	_SC_FILE_ATTRIBUTES,
#else
	-1,
#endif
	-1,
#if	defined(_SC_FILE_SYSTEM) || _ENUM__SC_FILE_SYSTEM
	_SC_FILE_SYSTEM,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_INT_MAX) || _ENUM__SC_INT_MAX
	_SC_INT_MAX,
#else
	-1,
#endif
#if	defined(_SC_INT_MIN) || _ENUM__SC_INT_MIN
	_SC_INT_MIN,
#else
	-1,
#endif
	-1,
	-1,
	-1,
#if	defined(_SC_LEVEL1_DCACHE_ASSOC) || _ENUM__SC_LEVEL1_DCACHE_ASSOC
	_SC_LEVEL1_DCACHE_ASSOC,
#else
	-1,
#endif
#if	defined(_SC_LEVEL1_DCACHE_LINESIZE) || _ENUM__SC_LEVEL1_DCACHE_LINESIZE
	_SC_LEVEL1_DCACHE_LINESIZE,
#else
	-1,
#endif
#if	defined(_SC_LEVEL1_DCACHE_SIZE) || _ENUM__SC_LEVEL1_DCACHE_SIZE
	_SC_LEVEL1_DCACHE_SIZE,
#else
	-1,
#endif
#if	defined(_SC_LEVEL1_ICACHE_ASSOC) || _ENUM__SC_LEVEL1_ICACHE_ASSOC
	_SC_LEVEL1_ICACHE_ASSOC,
#else
	-1,
#endif
#if	defined(_SC_LEVEL1_ICACHE_LINESIZE) || _ENUM__SC_LEVEL1_ICACHE_LINESIZE
	_SC_LEVEL1_ICACHE_LINESIZE,
#else
	-1,
#endif
#if	defined(_SC_LEVEL1_ICACHE_SIZE) || _ENUM__SC_LEVEL1_ICACHE_SIZE
	_SC_LEVEL1_ICACHE_SIZE,
#else
	-1,
#endif
#if	defined(_SC_LEVEL2_CACHE_ASSOC) || _ENUM__SC_LEVEL2_CACHE_ASSOC
	_SC_LEVEL2_CACHE_ASSOC,
#else
	-1,
#endif
#if	defined(_SC_LEVEL2_CACHE_LINESIZE) || _ENUM__SC_LEVEL2_CACHE_LINESIZE
	_SC_LEVEL2_CACHE_LINESIZE,
#else
	-1,
#endif
#if	defined(_SC_LEVEL2_CACHE_SIZE) || _ENUM__SC_LEVEL2_CACHE_SIZE
	_SC_LEVEL2_CACHE_SIZE,
#else
	-1,
#endif
#if	defined(_SC_LEVEL3_CACHE_ASSOC) || _ENUM__SC_LEVEL3_CACHE_ASSOC
	_SC_LEVEL3_CACHE_ASSOC,
#else
	-1,
#endif
#if	defined(_SC_LEVEL3_CACHE_LINESIZE) || _ENUM__SC_LEVEL3_CACHE_LINESIZE
	_SC_LEVEL3_CACHE_LINESIZE,
#else
	-1,
#endif
#if	defined(_SC_LEVEL3_CACHE_SIZE) || _ENUM__SC_LEVEL3_CACHE_SIZE
	_SC_LEVEL3_CACHE_SIZE,
#else
	-1,
#endif
#if	defined(_SC_LEVEL4_CACHE_ASSOC) || _ENUM__SC_LEVEL4_CACHE_ASSOC
	_SC_LEVEL4_CACHE_ASSOC,
#else
	-1,
#endif
#if	defined(_SC_LEVEL4_CACHE_LINESIZE) || _ENUM__SC_LEVEL4_CACHE_LINESIZE
	_SC_LEVEL4_CACHE_LINESIZE,
#else
	-1,
#endif
#if	defined(_SC_LEVEL4_CACHE_SIZE) || _ENUM__SC_LEVEL4_CACHE_SIZE
	_SC_LEVEL4_CACHE_SIZE,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_LONG_BIT) || _ENUM__SC_LONG_BIT
	_SC_LONG_BIT,
#else
	-1,
#endif
	-1,
#if	defined(_SC_MB_LEN_MAX) || _ENUM__SC_MB_LEN_MAX
	_SC_MB_LEN_MAX,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_NETWORKING) || _ENUM__SC_NETWORKING
	_SC_NETWORKING,
#else
	-1,
#endif
	-1,
#if	defined(_SC_NL_ARGMAX) || _ENUM__SC_NL_ARGMAX
	_SC_NL_ARGMAX,
#else
	-1,
#endif
#if	defined(_SC_NL_LANGMAX) || _ENUM__SC_NL_LANGMAX
	_SC_NL_LANGMAX,
#else
	-1,
#endif
#if	defined(_SC_NL_MSGMAX) || _ENUM__SC_NL_MSGMAX
	_SC_NL_MSGMAX,
#else
	-1,
#endif
#if	defined(_SC_NL_NMAX) || _ENUM__SC_NL_NMAX
	_SC_NL_NMAX,
#else
	-1,
#endif
#if	defined(_SC_NL_SETMAX) || _ENUM__SC_NL_SETMAX
	_SC_NL_SETMAX,
#else
	-1,
#endif
#if	defined(_SC_NL_TEXTMAX) || _ENUM__SC_NL_TEXTMAX
	_SC_NL_TEXTMAX,
#else
	-1,
#endif
	-1,
	-1,
#if	defined(_SC_NZERO) || _ENUM__SC_NZERO
	_SC_NZERO,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_PIPE) || _ENUM__SC_PIPE
	_SC_PIPE,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_SCHAR_MAX) || _ENUM__SC_SCHAR_MAX
	_SC_SCHAR_MAX,
#else
	-1,
#endif
#if	defined(_SC_SCHAR_MIN) || _ENUM__SC_SCHAR_MIN
	_SC_SCHAR_MIN,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_SHELL) || _ENUM__SC_SHELL
	_SC_SHELL,
#else
	-1,
#endif
#if	defined(_SC_SHRT_MAX) || _ENUM__SC_SHRT_MAX
	_SC_SHRT_MAX,
#else
	-1,
#endif
#if	defined(_SC_SHRT_MIN) || _ENUM__SC_SHRT_MIN
	_SC_SHRT_MIN,
#else
	-1,
#endif
#if	defined(_SC_SIGNALS) || _ENUM__SC_SIGNALS
	_SC_SIGNALS,
#else
	-1,
#endif
	-1,
#if	defined(_SC_SINGLE_PROCESS) || _ENUM__SC_SINGLE_PROCESS
	_SC_SINGLE_PROCESS,
#else
	-1,
#endif
	-1,
	-1,
	-1,
#if	defined(_SC_SSIZE_MAX) || _ENUM__SC_SSIZE_MAX
	_SC_SSIZE_MAX,
#else
	-1,
#endif
#if	defined(_SC_STREAMS) || _ENUM__SC_STREAMS
	_SC_STREAMS,
#else
	-1,
#endif
	-1,
	-1,
	-1,
#if	defined(_SC_SYSTEM_DATABASE) || _ENUM__SC_SYSTEM_DATABASE
	_SC_SYSTEM_DATABASE,
#else
	-1,
#endif
#if	defined(_SC_SYSTEM_DATABASE_R) || _ENUM__SC_SYSTEM_DATABASE_R
	_SC_SYSTEM_DATABASE_R,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_UCHAR_MAX) || _ENUM__SC_UCHAR_MAX
	_SC_UCHAR_MAX,
#else
	-1,
#endif
#if	defined(_SC_UINT_MAX) || _ENUM__SC_UINT_MAX
	_SC_UINT_MAX,
#else
	-1,
#endif
	-1,
#if	defined(_SC_ULONG_MAX) || _ENUM__SC_ULONG_MAX
	_SC_ULONG_MAX,
#else
	-1,
#endif
#if	defined(_SC_USER_GROUPS) || _ENUM__SC_USER_GROUPS
	_SC_USER_GROUPS,
#else
	-1,
#endif
#if	defined(_SC_USER_GROUPS_R) || _ENUM__SC_USER_GROUPS_R
	_SC_USER_GROUPS_R,
#else
	-1,
#endif
#if	defined(_SC_USHRT_MAX) || _ENUM__SC_USHRT_MAX
	_SC_USHRT_MAX,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_WORD_BIT) || _ENUM__SC_WORD_BIT
	_SC_WORD_BIT,
#else
	-1,
#endif
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
	-1,
#if	defined(_SC_XOPEN_XPG2) || _ENUM__SC_XOPEN_XPG2
	_SC_XOPEN_XPG2,
#else
	-1,
#endif
#if	defined(_SC_XOPEN_XPG3) || _ENUM__SC_XOPEN_XPG3
	_SC_XOPEN_XPG3,
#else
	-1,
#endif
#if	defined(_SC_XOPEN_XPG4) || _ENUM__SC_XOPEN_XPG4
	_SC_XOPEN_XPG4,
#else
	-1,
#endif
};
